name: Deploy to GitHub Pages Workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
      - 'main'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  deploy:
    environment:
      name: github-pages
      url: https://kelseymorsebrown.github.io/jammming/
    runs-on: ubuntu-latest
    needs: test
    env:
      CI: true
      REACT_APP_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Deploy to GitHub Pages
        id: deployment
        run: npm run deploy
