name: Deploy to GitHub Pages
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
      - 'main'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    needs: test
    uses: ./.github/workflows/build.yml
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: https://kelseymorsebrown.github.io/jammming/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
