name: Pull Request Open & Update Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}
jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
