name: Run Unit Tests
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
        run: npm run test
